using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class InteractLightGarden : MonoBehaviour, IReceiveSearch
{
    //ƒ‰ƒCƒg

    [SerializeField] private DialogueText GetText; //“d’r“όθ
    [SerializeField] private DialogueText AfterText;//“όθγ

    private GameManager gameManager;

    public void ReceiveSearch()
    {
        //κ‡‚Ι‚ζ‚Α‚Δ‚Νƒtƒ‰ƒO‚Ι‚ζ‚Α‚Δπ•ς
        //ηκ’ά‚π“όθ‚µ‚Δ‚Ά‚Θ‚Ά“όθ
        if (!gameManager.eventFlagData.itemDataBase.truthBullets[3].getFlag)
        {
            gameManager.OpenTextWindow(GetText);
        }
        //’Tυγ
        else
        {
            gameManager.OpenTextWindow(AfterText);
        }
    }

    void Start()
    {
        GameObject gm = GameObject.Find("GameManager");
        gameManager = gm.GetComponent<GameManager>();
    }

    void Update()
    {

    }
}
