using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class InteractWarehouseShelfBack : MonoBehaviour, IReceiveSearch
{
    //‘qΙ‰‚Μ’I

    [SerializeField] private DialogueText ClawGetText; //ηκ’ά“όθ
    [SerializeField] private DialogueText NormalText;//’Κν

    private GameManager gameManager;

    public void ReceiveSearch()
    {
        //κ‡‚Ι‚ζ‚Α‚Δ‚Νƒtƒ‰ƒO‚Ι‚ζ‚Α‚Δπ•ς
        //ηκ’ά‚π“όθ‚µ‚Δ‚Ά‚Θ‚Ά“όθ
        if (!gameManager.eventFlagData.itemDataBase.truthBullets[5].getFlag)
        {
            gameManager.OpenTextWindow(ClawGetText);
        }
        //’Tυγ
        else
        {
            gameManager.OpenTextWindow(NormalText);
        }
    }

    void Start()
    {
        GameObject gm = GameObject.Find("GameManager");
        gameManager = gm.GetComponent<GameManager>();
    }

    void Update()
    {

    }
}
